affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 3
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 1
sb_trainable: true
sp_trainable: true
state_id: 14
symbolic.funs_name.0:
- - x
  - '0'
  - x
  - '0'
  - x
  - '0'
  - 1/x^2
  - x
  - x
  - x
- - '0'
  - '0'
  - x
  - x
  - '0'
  - x
  - x
  - '0'
  - x
  - x
- - x
  - '0'
  - '0'
  - '0'
  - x
  - x
  - x
  - x
  - '0'
  - '0'
symbolic.funs_name.1:
- - cos
  - cos
  - cos
symbolic.funs_name.2:
- - cos
symbolic.funs_name.3:
- - tanh
symbolic_enabled: true
width:
- - 10
  - 0
- - 3
  - 0
- - 1
  - 0
- - 1
  - 0
- - 1
  - 0
